application/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls', namespace='core')),
]

blog/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^$', views.PostList.as_view(), name='all_posts'),
    url(r'^post/(?P<pk>\d+)/$', views.PostDetail.as_view(), name='post'),
    url(r'^edit/(?P<pk>\d+)/$', views.PostUpdate.as_view(), name='edit'),
    url(r'^new/$', views.PostCreate.as_view(), name='new'),
]

core/urls.py
from django.conf.urls import url, include
from django.contrib.auth.views import login, logout

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^comment/', include('comment.urls', namespace='comment')),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^logout/(?P<next_page>.*)/$', logout, name='logout'),
    url(r'^login/$', views.login_user, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^register/(?P<next_page>.*)/$', views.register, name='register'),
    url(r'^like/', include('like.urls', namespace='like')),
]

core/models.py
from django.db import models

# Create your models here.

user/models.py
from django.db import models
from django.conf import settings
from .templatetags.filename import filename
from django.contrib.contenttypes.models import ContentType
# Create your models here.
import blog
import like
import comment

from PIL import Image
import os

def crop(name):
    path = settings.MEDIA_ROOT + name
    img = Image.open(path)
    half_the_width = img.size[0] / 2
    half_the_height = img.size[1] / 2
    shift = min(half_the_width, half_the_height)
    cropped_img = img.crop(
        (
            half_the_width - shift,
            half_the_height - shift,
            half_the_width + shift,
            half_the_height + shift
        )
    )
    cropped_path = settings.MEDIA_ROOT + "cropped/" + name
    cropped_img.save(cropped_path)
    return cropped_path

class UserInfo(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                related_name='info',
                                verbose_name='Аккаунт')

    userpic = models.ImageField(verbose_name=u'Изображение',
                                default='/media/default-avatar.png')

    class Meta:
        verbose_name = u'Информация о пользователе'
        verbose_name_plural = u'Информация о пользователях'

    @property
    def get_rating(self):
        return like.models.Like.objects.filter(item_type=ContentType.objects.get_for_model(blog.models.Post), item_id__in=self.posts.all()).count() + \
               like.models.Like.objects.filter(item_type=ContentType.objects.get_for_model(comment.models.Comment), item_id__in=self.posts.all()).count()

    def save(self, *args, **kwargs):
        super(UserInfo, self).save(*args, **kwargs)
        crop(filename(self.userpic))
    def __str__(self):
        return self.user.username

core/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
import json
from user.models import UserInfo
from user.forms import UserInfoForm
from PIL import Image
from io import StringIO
import base64

def image_to_string(image):
    pic = StringIO()
    return StringIO(base64.b64decode(image))

def verify_image(image):
    image = Image.open(image_to_string(image))
    return image.verify()

#http://www.djangobook.com/en/2.0/chapter14.html
def register(request, next_page="/"):
    if request.method == 'POST':
        print(request.POST)
        form = UserCreationForm(request.POST)
        if form.is_valid():
            image = None #request.POST.get("userpic")
            print(image)

            if (image is None or verify_image(image)):
                new_user = form.save()
                user = authenticate(username=form.cleaned_data['username'],
                                        password=form.cleaned_data['password1'],
                                        )
                login(request, user)
                if (image):
                    print(image, image_to_string(image))
                    info = UserInfo(user=user, userpic=image_to_string(image))
                    info.save()
                else:
                    info = UserInfo(user=user)
                    info.save()


                    return HttpResponse(json.dumps({"success" : True, "next" : next_page}), content_type = "application/json")
            #return HttpResponse(json.dumps({"success" : False, 'errors': dict(user_info_form.errors.items())}), content_type = "application/json")
        return HttpResponse(json.dumps({"success" : False, 'errors': dict(form.errors.items())}), content_type = "application/json")

    form = UserCreationForm()
    return render(request, "core/register.html", {
        'form': form,
        'next_page': next_page,
    })

def login_user(request):
    username = password = None
    if request.POST:
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponse(json.dumps({"success" : True}),
                                    content_type = "application/json")
    return HttpResponse(json.dumps({"success" : False}),
                        content_type = "application/json")



def index(request):
    return redirect('core:blog:all_posts')

core/templates/core/base.html
{% load static %}
{% load markdown_filter %}

<head>
    <script src="https://code.jquery.com/jquery-2.2.3.min.js"
        integrity="sha256-a23g1Nt4dtEYOj7bR+vTu7+T8VP13humZFBJNIYoEJo="
        crossorigin="anonymous">
    </script>
    <link rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
        integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7"
        crossorigin="anonymous" />
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js">
    </script>
    <link rel="stylesheet"
          href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.4.0/styles/default.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.4.0/highlight.min.js">
    </script>
    <script src="http://gregpike.net/demos/bootstrap-file-input/bootstrap.file-input.js">
    </script>
    <script src="{% static 'like/like.js' %}"></script>
    <script src="{% static 'comment/edit.js' %}"></script>
    <link rel="stylesheet" href="{% static 'core/blog.css' %}" />
    {% block head %}

    {% endblock %}
</head>

<body>
    <div class="blog-masthead">
      <div class="container" data-active="{% block section %} {% endblock %}" id="menu">
        <nav class="blog-nav">
          <a id="menu-home" class="blog-nav-item" href="/">Posts</a>
          <a id="menu-users" class="blog-nav-item" href="{% url 'core:user:users' %}">Users</a>
          <a id="menu-new-post" class="blog-nav-item" href="{% url 'core:blog:new' %}"> New post </a>
          {% if user.is_anonymous %}
            <a id="menu-login" class="login-button blog-nav-item pull-right" href="#"> Login </a>
          {% else %}
            <a class="blog-nav-item pull-right" href="{% url 'core:logout' request.path %}"> Logout </a>
            <span class="blog-nav-item pull-right"> Howdy, {{ user.username }}? </span>

          {% endif %}
        </nav>
      </div>
    </div>
    {% include "core/login_popup.html" %}
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-sm-offset-2 blog-header">
                <h1 class="blog-title text-center">
                    {% block title %}
                    {% endblock %}
                </h1>
                <p class="lead blog-description">
                </p>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-10 col-sm-offset-1 blog-main">
                {% block content %}
                {% endblock %}
            </div> <!-- /.blog-main -->
        </div> <!-- /.row -->
    </div>

    <script src="{% static 'core/blog.js' %}">
    </script>
</body>

core/templates/core/login_popup.html
<div class="container">
  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header" style="padding:35px 50px;">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4><span class="glyphicon glyphicon-lock"></span> Login</h4>
        </div>
        <div class="modal-body" style="padding:40px 50px;">
          <div class="alert alert-danger" style="display:none" id="incorrect-credentials">
            Incorrect login or password
          </div>
          <form role="form" id="login_form" method="post" action="{% url 'core:login' %}">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{request.path}}" />
            <div class="form-group">
              <label for="username"><span class="glyphicon glyphicon-user"></span> Username</label>
              <input type="text" class="form-control" name="username" id="username" placeholder="Enter username">
            </div>
            <div class="form-group">
              <label for="psw"><span class="glyphicon glyphicon-eye-open"></span> Password</label>
              <input type="password" class="form-control" name="password" id="psw" placeholder="Enter password">
            </div>
            <!--<div class="checkbox">
              <label><input type="checkbox" value="" checked>Remember me</label>
          </div>-->
              <button type="submit" class="btn btn-primary btn-block"><span class="glyphicon glyphicon-off"></span> Login</button>
          </form>
        </div>
        <div class="modal-footer">
          <!-- <button type="submit" class="btn btn-danger btn-default pull-left" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cancel</button>-->
          <p>Not a member? <a href="{% url 'core:register' request.path %}">Sign Up</a></p>
          <!--<p>Forgot <a href="#">Password?</a></p>-->
        </div>
      </div>

    </div>
  </div>
</div>

<div class="container">
  <!-- Modal -->
  <div class="modal fade" id="error-modal" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header modal-error">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title modal-error">Oops! We have encountered an error</h4>
        </div>
        <div class="modal-body">
          <p id="error-modal-error-text">Some text in the modal.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>

</div>

<div class="hidden" id="ajax-data" data-csrf="{{ csrf_token }}"
                                   data-url="{% url 'core:login' %}">
</div>

<script>
$(document).ready(function() {
    $(".glyphicon-eye-open").mousedown(function() {
        $("#psw, #psw-register").attr("type", "text");
    });
    $(".glyphicon-eye-open").mouseup(function() {
        $("#psw, #psw-register").attr("type", "password");
    });
});
</script>

core/templates/core/register.html
{% extends "core/base.html" %}

{% block section %}menu-login{% endblock %}

{% block title %}Регистрация{% endblock %}

{% block content %}

<form role="form" id="register-form">
  <div class="alert alert-danger" style="display:none" id="incorrect-credentials-register">
  </div>
  <div class="form-group">
    <label for="username"><span class="glyphicon glyphicon-user"></span> Username</label>
    <input type="text" placeholder="30 characters or fewer. Letters, digits and @/./+/-/_ only" class="form-control" id="username-register">
  </div>
  <div class="form-group">
    <label for="psw"><span class="glyphicon glyphicon-eye-open"></span> Password</label>
    <input type="password" placeholder="Not too simple. At least 8 characters" class="form-control" id="psw-register">
  </div>
  <!--<div class="form-group">
      <label for="id_userpic"><span class="glyphicon glyphicon-folder-open"></span> Userpic</label>

      <input class="btn btn-primary" id="id_userpic" name="userpic" type="file" /></p>
  </div>-->
  <button type="submit" class="btn btn-primary btn-block"><span class="glyphicon glyphicon-off"></span> Sign up</button>
</form>

<div class="hidden" id="ajax-register-data" data-url="{% url 'core:register' next_page %}">
</div>

<script>
$(document).ready(function() {
    $("#register-form").submit(function(event) {
        $("#incorrect-credentials-register").fadeOut();
        $("#incorrect-credentials-register").text("");
        event.preventDefault();
        var csrf = $("#ajax-data").data("csrf");
        var registerUrl = $("#ajax-register-data").data("url");
        $.ajax({
            url : registerUrl,
            type : "POST",
            data : { "username": $("#username-register").val(),
                     "password1": $("#psw-register").val(),
                     "password2": $("#psw-register").val(),
                     /*"userpic": $("#id_userpic").val(), */
                     "csrfmiddlewaretoken": csrf}, // data sent with the post request
            // handle a successful response
            success : function(json) {
                if (json["success"]) {
                    console.log("SUCCESS");
                    console.log(json)
                    window.location.assign(json["next"])
                } else {
                    console.log("FAIL");
                    console.log(json);
                    var error_set = {}
                    for (var reason in json["errors"]) {
                        for (var error in json["errors"][reason]) {
                            error_set[json["errors"][reason][error]] = 1;
                        }
                    }
                    for (var error in error_set) {
                        $("#incorrect-credentials-register").append(error + "<br>");
                    }
                    $("#incorrect-credentials-register").fadeIn();
                }
            },

            // handle a non-successful response
            error : function(xhr, errmsg, err) {
                $("#error-modal-error-text").html(errmsg + "\n" + xhr.status + ": " + xhr.responseText);
                $("#error-modal").modal();
            }
        });
    });
});
</script>

{% endblock %}